repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v17.0.6
    hooks:
      - id: clang-format
  #- repo: https://github.com/cpplint/cpplint
  #  rev: 2.0.0
  #  hooks:
  #    - id: cpplint
  #      #exclude: 'public/.*\.cpp|downloads/.*\.cpp'
  #- repo: https://github.com/cpp-linter/cpp-linter-hooks
  #  rev: v0.6.0
  #  hooks:
  #    - id: clang-tidy